name: Run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        mongodb-version: ['4.2']

    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.6.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - name: Install dependencies
      run: npm install
      working-directory: ./src

    - name: Run Linting
      run: npm run test-lint
      working-directory: ./src

    - name: Run Unit Tests
      run: npm run test-unit
      working-directory: ./src

    - name: Run Integration Tests
      run: npm run test-integration
      working-directory: ./src

    - name: Start the application
      run: npm start &
      working-directory: ./src

    - name: Wait for the server to be ready
      run: sleep 25 # Adjust this based on your server's startup time

    - name: Run End-to-End Tests
      run: npm run test-e2e
      working-directory: ./src
      env:
        CI: true
