name: Run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        mongodb-version: ['4.2']

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Playwright dependencies
      run: npx playwright install-deps
      working-directory: ./src

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.6.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libnss3 libxss1 libasound2
      working-directory: ./src

    - name: Install Node.js dependencies
      run: npm install
      working-directory: ./src

    - name: Run Linting
      run: npm run test-lint
      working-directory: ./src

    - name: Run Unit Tests
      run: npm run test-unit
      working-directory: ./src

    - name: Run Integration Tests
      run: npm run test-integration
      working-directory: ./src

    - name: Start the application and wait for it to be ready
      run: |
        npm start &  # Start the server in the background
        npx wait-on http://localhost:3000  # Wait until the server is up
      working-directory: ./src

    - name: Run End-to-End Tests with Debugging
      run: DEBUG=pw:api npm run test-e2e
      working-directory: ./src
      env:
        CI: true

    - name: Run End-to-End Tests without sandbox (optional)
      if: failure()
      run: npx playwright test --browser chromium --no-sandbox
      working-directory: ./src
      env:
        CI: true

    - name: Upload Debug Logs
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: debug-logs
        path: /home/runner/.npm/_logs/
